### ISSUE TITLE
Sehr geehrter Herr h0rd

### ISSUE THREAD

**Issue by profiluefter** [BrudaSchui/PLFPrep_Pairprogramming#1]
Der Projektantrag war noch nicht freigegeben. Wie können Sie es wagen bereits an der Anforderungsspezifikation zu arbeiten!

Komplett illegal du depp

**Comment by noassl** [comment]
Sehr geehrter Lüfter Profi,

Hier scheint ein Missverständnis vorzuliegen. Nach intensiven Handauflegen-Sessions mit dem Hausmeister meines Vertrauens befindet sich dieses Projekt mit seinen Projektmitarbeitern aktuell in der Brainstorming-Phase, eine Anforderungsspezifikation wird frühestens zu Ostern begonnen. Alle Dokumente, die bis jetzt fertiggestellt wurden, sind sowohl freigegeben als auch im letzten Projektstatusbericht zu finden. Zu weiteren Fragen wenden Sie sich bitte an die Rechtsabteilung (support@docsced.at) der noaßl AG Ltd.
