### ISSUE TITLE
Frage zum Projekt

### ISSUE THREAD

**Issue by EinboeckFranz** [BrudaSchui/PLFPrep_Pairprogramming#2]
Guten Tag,

ich habe eine Frage. 

Mit fragenden Grüßen

**Comment by noassl** [comment]
# Antwort zur Frage zum Projekt

## Einleitung

**ande du spast**

## Evaluierung

hod guad passt

## Chartanalyse

Obwesenheit in SYP: +37.10%
Lewahittn: %++ (SIIIIIIIMOOOON $)

## Ideenfindungsphase

heid damma nix

## Zusammenfassung

ok.

## Abschließend

dankeebenfoiswiedaschaun


*hosted with <3 by KlauslDota*  
*sponsored by Wotabert's Wotabyte*

**Comment by EinboeckFranz** [comment]
Sehr geehrter Herr!
Vielen Dank für diese aufschlussreiche Antwort.
MFG
